version: "3.8"

services:
  boleylapanel:
    build: ./backend
    container_name: boleylapanel
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - boleylanet

  mysql:
    image: mysql:8
    container_name: boleylapanel-mysql
    restart: always
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - boleylanet

volumes:
  mysql_data:

networks:
  boleylanet:
