version: '3.8'

services:
  mysql:
    image: mysql:lts
    container_name: boleylapanel-mysql
    restart: always
    network_mode: host
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --mysqlx=OFF
      - --bind-address=127.0.0.1
      - --character_set_server=utf8mb4
      - --collation_server=utf8mb4_unicode_ci
      - --log-bin=mysql-bin
      - --binlog_expire_logs_seconds=1209600
      - --host-cache-size=0
      - --innodb-open-files=1024
      - --innodb-buffer-pool-size=256M
      - --innodb-log-file-size=64M
      - --innodb-log-files-in-group=2
      - --general_log=0
      - --slow_query_log=1
      - --slow_query_log_file=/var/lib/mysql/slow.log
      - --long_query_time=2
    volumes:
      - /var/lib/boleylapanel/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boleylapanel-backend
    restart: always
    network_mode: host
    env_file: .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /var/lib/boleylapanel:/var/lib/boleylapanel
      - /var/lib/boleylapanel/logs:/var/lib/boleylapanel/logs
